In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)
type(array1)

[1 2 3 4 5]


numpy.ndarray

In [3]:
array1.shape #one dimetional array

(5,)

In [4]:
array1[4] #one dimentional print 5th element

5

In [5]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
array2=np.array([list1,list2,list3]) #create 2 dimensionl array
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
array2.shape  #print the shape of array, 3 row 4 column

(3, 4)

In [7]:
array2.reshape(2,6)  #reshaping the array but elements coint should be same

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
array2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
#retrive data from array
#array index start from 0
array2[:,:]  #will retrive all the elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2[0:2,:]              #[row,column] [0:2,:] row: start from 0 and go before 2; : all columns

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
array2[0:2,0:2]   # row from 0 to before 2; column fro 0 to before 2, i.e. 1

array([[1, 2],
       [5, 6]])

In [12]:
#print 7,8,11,12, row 1 to 2; column 2,3
array2[1:,2:]   #last row and column need to be mentioned blanl [1:,2:]

array([[ 7,  8],
       [11, 12]])

In [13]:
array3= np.arange(0,10,2) #create a 1dimestional array, start=0, end=10, interval=2
array3

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(1,10,50)  #equally divided 1 to 10 in 50 points

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [29]:
#broad casting
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=arr1
print(arr2)
arr1[3:]=100  #put the value from 3 rd value to all 100 called broadcasting
print(arr1)
print(arr2)
#we can see by changing the value of arr1 also changing the value of arr2
# because array is a reference type
#arr1 and arr2 refer the same pointer thats why change in arr1 change the arr2
#to over come this we have .copy function

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3 100 100 100 100 100 100 100]
[  1   2   3 100 100 100 100 100 100 100]


In [33]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=arr1.copy()
arr1[4:]=100
print(arr1)
print(arr2)
#now the change in arr1 will not effect the arr2

[  1   2   3   4 100 100 100 100 100 100]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
val=2
print(arr2<=val)
print(arr2*2) #all the element in arr2 will be multiply by 2
arr3=arr2*2
print(arr3)
print(arr2)

[ True  True False False False False False False False False]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
array4=np.arange(0,20).reshape(4,5)
array4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
np.random.rand(5,4)  #Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)

array([[0.21327412, 0.96008631, 0.60608043, 0.03970571],
       [0.77174049, 0.24468489, 0.71451207, 0.6665786 ],
       [0.80693513, 0.35318616, 0.14340822, 0.81863352],
       [0.86449357, 0.90601775, 0.08541564, 0.32758827],
       [0.11763369, 0.39085668, 0.35854043, 0.63643613]])

In [54]:
np.random.randn(6,9) #Return a sample (or samples) from the "standard normal" distribution.

array([[-1.27535091, -1.01665493,  0.0522023 , -0.13995896, -0.70242757,
        -0.06753696,  1.37439816,  0.0096636 , -0.46721846],
       [-0.12982942, -0.5649375 ,  1.53914126,  0.69400474, -0.36913308,
        -0.20234986, -0.77356201, -2.03728904,  0.74460976],
       [ 0.24376099,  0.07228235, -0.34016641, -0.89484913, -1.48858414,
        -0.73235579,  0.96792489,  0.35020192, -0.03354015],
       [ 0.60362216, -0.83523432, -1.53576143, -0.32381964, -0.15939058,
        -0.63290217,  0.09700399, -1.89655722,  0.62289053],
       [-1.43246015, -0.70593393, -0.86590136, -0.75758285, -0.10373353,
        -1.0699491 , -0.09589628,  1.47121663,  0.3050705 ],
       [-0.17617281, -0.77428817,  0.55835177,  0.55755499, -1.35573504,
        -1.15617773,  0.16187241, -0.64820963,  1.16961889]])

In [59]:
np.random.randint(0,100,10)   #chose between 0 to 100, with 10 numbers, 1d array

array([26, 39, 43, 37, 18, 11, 89, 76, 29, 85])

In [58]:
np.random.randint(0,100,8).reshape(4,2) #reshape the value in 2d array

array([[13, 29],
       [36, 20],
       [81, 87],
       [55, 95]])

In [62]:
np.random.random_sample((2,3))  #Return random floats in the half-open interval [0.0, 1.0).

array([[0.87171559, 0.55257246, 0.45000076],
       [0.05475231, 0.61698533, 0.51111941]])