In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5,6,7,8,9,10,11,12]
arr=np.array(list1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
arr=arr.reshape(3,4)
print(arr.shape)
arr.reshape(2,6)
print(arr)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr[2][1]  #1 element

10

In [5]:
arr[2,1]  #same as above

10

In [6]:
#extract multiple element
arr[0:2,1:2]  #0 to 1 row, 1to 1 column

array([[2],
       [6]])

In [7]:
print(arr[0:2])  ##0 to 1 row, all column
print('//////////////')
print(arr[:2,:2])  #0 to 1row, 0 to 1 column
print('//////////////')
print(arr[:,:]) #all row and all column
print('//////////////')
print(arr[-1,0:2])  #-1 menas last row
print('//////////////')

[[1 2 3 4]
 [5 6 7 8]]
//////////////
[[1 2]
 [5 6]]
//////////////
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
//////////////
[ 9 10]
//////////////


In [8]:
arr1=np.arange(0,15,1).reshape(3,5)  #0 to 15, size of 1 increase# default size is 1
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
print(arr1>=2)

print(arr1[arr1>=2])   #element >= 2

[[False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
arr2=(arr1*2).copy()

In [11]:
print(arr2)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [12]:
np.random.random(10).reshape(2,5)  #10 random number between 0 to 1

array([[0.094646  , 0.28296579, 0.82750784, 0.99527308, 0.85271349],
       [0.46456626, 0.41098703, 0.32841325, 0.11682045, 0.30053805]])

In [13]:
np.random.randint(0,10,5)  #give 5 random number from 0 to 10

array([8, 1, 4, 9, 9])

In [14]:
np.random.rand(5,5)  #Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)

array([[0.71289584, 0.66771307, 0.08368039, 0.1041722 , 0.45371016],
       [0.82057796, 0.65879606, 0.16787798, 0.94739819, 0.3247959 ],
       [0.15395323, 0.49794171, 0.50139792, 0.20683208, 0.85732579],
       [0.59500468, 0.29969028, 0.08961186, 0.03454179, 0.87951747],
       [0.37276866, 0.51666985, 0.06306379, 0.32849417, 0.95070633]])

In [15]:
np.random.randn(5,5) #Return a sample (or samples) from the "standard normal" distribution

array([[-1.08228099, -0.99657543, -0.2970138 ,  0.23646372, -1.14227157],
       [ 1.10973154, -0.72223722,  1.18058672, -0.47530623, -0.12639345],
       [-1.18473022, -1.60735662, -0.7894357 , -0.65422224,  0.27795014],
       [-0.13962861,  1.22797219, -0.55230591, -0.36549041,  0.72339533],
       [ 1.17368913, -0.97366601,  1.1328765 ,  0.16133298,  0.50466427]])

In [16]:
l1=range(10)  #create a list in python
l2=range(10,20)
print(l1[7])

7


In [17]:
ar1=np.array(l1)
ar2=np.array(l2)
print(ar1)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [18]:
# + and- operation in numpy array, we can do / and * operations
print(ar1+ar2)
print(ar1-ar2)

[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]


In [19]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)  #or float
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
a.itemsize # 8 for float

8

In [21]:
np.zeros((2,3))
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
a=np.linspace(2,8,10).reshape(2,5) #between 2 and 8 with 5 linear space
a

array([[2.        , 2.66666667, 3.33333333, 4.        , 4.66666667],
       [5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ]])

In [23]:
print(a.min())   #minimum and maximum
print(a.max())
print(a.sum())  #sum of all elememt

2.0
8.0
50.0


In [24]:
a.sum(axis=0)   #axis=0 means column sum

array([ 7.33333333,  8.66666667, 10.        , 11.33333333, 12.66666667])

In [25]:
a.sum(axis=1)  #row sum and give a raary

array([16.66666667, 33.33333333])

In [26]:
np.std(a)  #standard deviation of all number

1.9148542155126762

In [27]:
# iterate throgh array
for i in a:  #it will iterate throgh row
    print(i)  #print row
    for j in i:  #print individual item in row as row is list it can iterrate again
        print(j)

[2.         2.66666667 3.33333333 4.         4.66666667]
2.0
2.6666666666666665
3.333333333333333
4.0
4.666666666666666
[5.33333333 6.         6.66666667 7.33333333 8.        ]
5.333333333333333
6.0
6.666666666666666
7.333333333333333
8.0


In [39]:
# to print each element in array

for i in a.flat:  #flatten is function
    print(i)

2.0
2.6666666666666665
3.333333333333333
4.0
4.666666666666666
5.333333333333333
6.0
6.666666666666666
7.333333333333333
8.0


In [29]:
# ~Stacking 2 array together

a1=np.arange(0,10).reshape(5,2)
print(a1)
a2=np.arange(10,20).reshape(5,2)
print(a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [30]:
#Horizontal Stacking
np.hstack((a1,a2))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [31]:
#Vertical Stacking
np.vstack((a1,a2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [32]:
#Split the array

a3= np.arange(0,30).reshape(2,15)
print(a3)
result=np.hsplit(a3,3)  #split a3 into 3 slice and store the result into variable #bSplit an array into multiple sub-arrays horizontally (column-wise).

for i in result:
    print(i)  #print the 3 resulant array
#sameway array can split in vertically by hsplit

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [33]:
#sameway array can split in vertically by hsplit
result1=np.vsplit(a3,2)  #Split an array into multiple sub-arrays vertically (row-wise).

for i in result1:
    print(i)  #print the 3 resulant array

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [34]:
print(a3>7)  #a3 elements greter than 7 boolean
b=a3>7
print(a3[b]) #print the elements in array >7
# want to replace the elements >7 by -1

a3[b]=-1
print(a3)

[[False False False False False False False False  True  True  True  True
   True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True]]
[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[ 0  1  2  3  4  5  6  7 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


# Iterate array via nditer

In [36]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
for i in np.nditer(a1,order='F'):  #order C go row by row same effect as flatten, ordef F will go column wise
    print(i)

0
1
2
3
4
5
6
7
8
9


In [56]:
for i in np.nditer(a1,order='F',flags=['external_loop']):  #external_loop, each iteration will  print entire column 
    print(i)

[0 2 4 6 8]
[1 3 5 7 9]


In [57]:
for i in np.nditer(a1,order='C',flags=['external_loop']):  #external_loop, all data will print in one column
    print(i)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
#iterate through array and want to modify the elements, can be done via op_flags
for i in np.nditer(a1,op_flags=['readwrite']):
    i[...]=i+1
    print(i)
a1

[ 3  5  7  9 11]
[ 4  6  8 10 12]


array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [62]:
for i in np.nditer(a1,order='F',flags=['external_loop'],op_flags=['readwrite']):
    i[...]=i+1
    a4=i
a4

array([ 5,  7,  9, 11, 13])

# iterate throgh numpy array in Fortran order and store in another array

In [92]:
 j=0
 k=np.zeros((2,5),dtype=int)
k=np.empty((2,5),dtype=int)
#iterate throgh numpy array in Fortran order and store in another array
#external_loop`` causes the ``values`` given to be one-dimensional arrays with multiple values instead of zero-dimensional arrays
for i in np.nditer(a1,order='F',flags=['external_loop']): 
    print(type(i))
    print(k[j])
    print(i)
    k[j]=i
    print(j)
    print(k)
    j=j+1
k
a1

<class 'numpy.ndarray'>
[         0 1075052544          0 1075576832          0]
[ 4  6  8 10 12]
0
[[         4          6          8         10         12]
 [1075970048          0 1076232192          0 1076494336]]
<class 'numpy.ndarray'>
[1075970048          0 1076232192          0 1076494336]
[ 5  7  9 11 13]
1
[[ 4  6  8 10 12]
 [ 5  7  9 11 13]]


array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

# Iterate through 2 different Arrays

In [103]:
ars=np.arange(0,9).reshape(3,3)
ars1=np.arange(10,13).reshape(3,1)
print(ars)
print(ars1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10]
 [11]
 [12]]


In [105]:
for x,y in np.nditer([ars,ars1]):  #array shape should be compatible
    print(x,y)

0 10
1 10
2 10
3 11
4 11
5 11
6 12
7 12
8 12
