In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.arange(0,20).reshape(5,4)
df=pd.DataFrame(a,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [30]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [4]:
df.to_csv('test2.csv')

In [5]:
df1=pd.DataFrame(a)
print(df1)
df1.to_csv('test3.csv')

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19


In [36]:
df['col1']['row2']  #1st col and then row

4

In [7]:
#Accesing elements from data frame
print(df.loc['row1']) #return the column
# df.loc
print(df.loc['row2','col2'])  #row2, col1
print(df.loc[['row1','row2']])  ##multiple row need to mentioned as list
print(df.loc['row1':'row2','col1':'col2'])  #multiple row and multiple  column
#*******'row1':'row2'  both location should be sepearted by different ''

# The difference between the loc and iloc functions is that the loc function selects rows using row labels (e.g. tea) 
# whereas the iloc function selects rows using their integer positions (staring from 0 and going up by one for each row).

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int32
5
      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
      col1  col2
row1     0     1
row2     4     5


In [8]:
df.iloc[0:2,1:2]  #same as numpy by must be mentioed by row, column index not by name

col2
row1     1
row2     5

In [9]:
#convert the data frame to arrays by .values 
print(df.iloc[:,:].values)
print(df.iloc[:,:].values.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [27]:
df['col1'].value_counts() #count of the values in one col row wise
#suppose in data we have category features, if we need to count the unique categories

col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [28]:
df['col1'].unique()  #see the unique valus

array([ 0,  4,  8, 12, 16])

In [26]:
df.loc['row1':'row2','col1':'col2'].value_counts()

col1  col2
0     1       1
4     5       1
Name: count, dtype: int64

In [57]:
df2=pd.read_csv('mercedesbenz.csv',index_col=0) #or index_col='ID'
df2

y  X0 X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  \
ID                                            ...                           
0     130.81   k  v  at  a  d   u  j  o    0  ...     0     0     1     0   
6      88.53   k  t  av  e  d   y  l  o    0  ...     1     0     0     0   
7      76.26  az  w   n  c  d   x  j  x    0  ...     0     0     0     0   
9      80.62  az  t   n  f  d   x  l  e    0  ...     0     0     0     0   
13     78.02  az  v   n  f  d   h  d  n    0  ...     0     0     0     0   
...      ...  .. ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   
8405  107.39  ak  s  as  c  d  aa  d  q    0  ...     1     0     0     0   
8406  108.77   j  o   t  d  d  aa  h  h    0  ...     0     1     0     0   
8412  109.22  ak  v   r  a  d  aa  g  e    0  ...     0     0     1     0   
8415   87.48  al  r   e  f  d  aa  l  u    0  ...     0     0     0     0   
8417  110.85   z  r  ae  c  d  aa  g  w    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
ID                                        
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
7        0     0     1     0     0     0  
9        0     0     0     0     0     0  
13       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
8405     0     0     0     0     0     0  
8406     0     0     0     0     0     0  
8412     0     0     0     0     0     0  
8415     0     0     0     0     0     0  
8417     0     0     0     0     0     0  

[4209 rows x 377 columns]

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4209 entries, 130.81 to 110.85
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB


In [58]:
df2['X0'].value_counts() #type of categorical value and count

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [59]:
# df3=pd.DataFrame()
df2[df2['X375']>2]

Empty DataFrame
Columns: [y, X0, X1, X2, X3, X4, X5, X6, X8, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X26, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, X47, X48, X49, X50, X51, X52, X53, X54, X55, X56, X57, X58, X59, X60, X61, X62, X63, X64, X65, X66, X67, X68, X69, X70, X71, X73, X74, X75, X76, X77, X78, X79, X80, X81, X82, X83, X84, X85, X86, X87, X88, X89, X90, X91, X92, X93, X94, X95, X96, X97, X98, X99, X100, X101, X102, ...]
Index: []

[0 rows x 377 columns]

In [53]:
df2['X375']>8

y
130.81    False
88.53     False
76.26     False
80.62     False
78.02     False
          ...  
107.39    False
108.77    False
109.22    False
87.48     False
110.85    False
Name: X375, Length: 4209, dtype: bool

In [66]:
df2['X1'].dtypes  #type of data in one column

dtype('O')

In [76]:
df3=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)
df3

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [72]:
df3.to_json(orient='records')

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [2]:
import html5lib
# url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
url='https://en.wikipedia.org/wiki/Mobile_country_code'
dfh=pd.read_html(url,match='Mobile country code',header=0,index_col='Country') #dfh is the list of table present in the webpage #index_col='Country'
df4=dfh[0] #is the 1st table , i.e. data frame
df4

Mobile country code ISO 3166  \
Country                                                                   
A Abkhazia                                                 289    GE-AB   
Afghanistan                                                412       AF   
Albania                                                    276       AL   
Algeria                                                    603       DZ   
American Samoa (United States of America)                  544       AS   
...                                                        ...      ...   
Vietnam                                                    452       VN   
W Wallis and Futuna                                        543       WF   
Y Yemen                                                    421       YE   
Z Zambia                                                   645       ZM   
Zimbabwe                                                   648       ZW   

                                                                        Mobile network codes  \
Country                                                                                        
A Abkhazia                                          List of mobile network codes in Abkhazia   
Afghanistan                                      List of mobile network codes in Afghanistan   
Albania                                              List of mobile network codes in Albania   
Algeria                                              List of mobile network codes in Algeria   
American Samoa (United States of America)     List of mobile network codes in American Samoa   
...                                                                                      ...   
Vietnam                                          List of mobile network codes in the Vietnam   
W Wallis and Futuna                        List of mobile network codes in Wallis and Futuna   
Y Yemen                                            List of mobile network codes in the Yemen   
Z Zambia                                              List of mobile network codes in Zambia   
Zimbabwe                                            List of mobile network codes in Zimbabwe   

                                          National MNC authority  \
Country                                                            
A Abkhazia                                                   NaN   
Afghanistan                                                  NaN   
Albania                                                      NaN   
Algeria                                                      NaN   
American Samoa (United States of America)                    NaN   
...                                                          ...   
Vietnam                                                      NaN   
W Wallis and Futuna                                          NaN   
Y Yemen                                                      NaN   
Z Zambia                                                     NaN   
Zimbabwe                                                     NaN   

                                                            Remarks  
Country                                                              
A Abkhazia                                 MCC is not listed by ITU  
Afghanistan                                                     NaN  
Albania                                                         NaN  
Algeria                                                         NaN  
American Samoa (United States of America)                       NaN  
...                                                             ...  
Vietnam                                                         NaN  
W Wallis and Futuna                                             NaN  
Y Yemen                                                         NaN  
Z Zambia                                                        NaN  
Zimbabwe                                                        NaN  

[252 rows x 5 columns]

In [10]:
df4[2:6]  #print row number 2to 5 like list

Mobile country code ISO 3166  \
Country                                                                   
Albania                                                    276       AL   
Algeria                                                    603       DZ   
American Samoa (United States of America)                  544       AS   
Andorra                                                    213       AD   

                                                                     Mobile network codes  \
Country                                                                                     
Albania                                           List of mobile network codes in Albania   
Algeria                                           List of mobile network codes in Algeria   
American Samoa (United States of America)  List of mobile network codes in American Samoa   
Andorra                                           List of mobile network codes in Andorra   

                                          National MNC authority Remarks  
Country                                                                   
Albania                                                      NaN     NaN  
Algeria                                                      NaN     NaN  
American Samoa (United States of America)                    NaN     NaN  
Andorra                                                      NaN     NaN

In [30]:
df4['Mobile country code'].min(), df4['Mobile country code'].max(), df4['Mobile country code'].mean()

(202, 995, 459.80555555555554)

In [55]:
# dir(df4)  #in python dir to print all the property

df5=df4[ (df4['Mobile country code']==603) | (df4['ISO 3166']=='AS') ]  #store the value in another data frame where country code is 603
df5

Mobile country code ISO 3166  \
Country                                                                   
Algeria                                                    603       DZ   
American Samoa (United States of America)                  544       AS   

                                                                     Mobile network codes  \
Country                                                                                     
Algeria                                           List of mobile network codes in Algeria   
American Samoa (United States of America)  List of mobile network codes in American Samoa   

                                          National MNC authority Remarks  
Country                                                                   
Algeria                                                      NaN     NaN  
American Samoa (United States of America)                    NaN     NaN

In [37]:
df4.columns

Index(['Mobile country code', 'ISO 3166', 'Mobile network codes',
       'National MNC authority', 'Remarks'],
      dtype='object')

In [42]:
df4[['Mobile country code', 'ISO 3166', 'Mobile network codes']]  #multple custom columns

Mobile country code ISO 3166  \
Country                                                                   
A Abkhazia                                                 289    GE-AB   
Afghanistan                                                412       AF   
Albania                                                    276       AL   
Algeria                                                    603       DZ   
American Samoa (United States of America)                  544       AS   
...                                                        ...      ...   
Vietnam                                                    452       VN   
W Wallis and Futuna                                        543       WF   
Y Yemen                                                    421       YE   
Z Zambia                                                   645       ZM   
Zimbabwe                                                   648       ZW   

                                                                        Mobile network codes  
Country                                                                                       
A Abkhazia                                          List of mobile network codes in Abkhazia  
Afghanistan                                      List of mobile network codes in Afghanistan  
Albania                                              List of mobile network codes in Albania  
Algeria                                              List of mobile network codes in Algeria  
American Samoa (United States of America)     List of mobile network codes in American Samoa  
...                                                                                      ...  
Vietnam                                          List of mobile network codes in the Vietnam  
W Wallis and Futuna                        List of mobile network codes in Wallis and Futuna  
Y Yemen                                            List of mobile network codes in the Yemen  
Z Zambia                                              List of mobile network codes in Zambia  
Zimbabwe                                            List of mobile network codes in Zimbabwe  

[252 rows x 3 columns]

In [41]:
df4['ISO 3166'].unique()

array(['GE-AB', 'AF', 'AL', 'DZ', 'AS', 'AD', 'AO', 'AI', 'AG', 'AR',
       'AM', 'AW', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE',
       'BZ', 'BJ', 'BM', 'BT', 'BO', 'BQ', 'BA', 'BW', 'BR', 'IO', 'VG',
       'BN', 'BG', 'BF', 'BI', 'KH', 'CM', 'CA', 'CV', 'KY', 'CF', 'TD',
       'CL', 'CN', 'CO', 'KM', 'CG', 'CK', 'CR', 'HR', 'CU', 'CW', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'TL', 'EC', 'EG', 'SV', 'GQ',
       'ER', 'EE', 'ET', 'FK', 'FO', 'FJ', 'FI', 'FR', 'GF', 'RE', 'YT',
       'PF', 'GA', 'GM', 'GE', 'DE', 'GH', 'GI', 'GR', 'GL', 'GD', 'GP',
       'GU', 'GT', 'GG', 'GN', 'GW', 'GY', 'HT', 'HN', 'HK', 'HU', 'IS',
       'IN', 'ID', 'IR', 'IQ', 'IE', 'IM', 'IL', 'IT', 'CI', 'JM', 'JP',
       'JE', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'RS-KM', 'KW', 'KG',
       'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MK',
       'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MQ', 'MR', 'MU', 'MX',
       'FM', 'MD', 'MC', 'MN', 'ME', 'MS', 'MA', 'MZ', 'M

In [116]:
df4.iloc[:,0:1]

Mobile country code
Country                                                       
A Abkhazia                                                 289
Afghanistan                                                412
Albania                                                    276
Algeria                                                    603
American Samoa (United States of America)                  544
...                                                        ...
Vietnam                                                    452
W Wallis and Futuna                                        543
Y Yemen                                                    421
Z Zambia                                                   645
Zimbabwe                                                   648

[252 rows x 1 columns]

In [117]:
df4['Mobile country code']['Afghanistan']  #column then row

412

In [118]:
df4.loc['A Abkhazia':'Algeria','Mobile country code':'ISO 3166']  ##iloc index name can pass and the column name to be displayed

Mobile country code ISO 3166
Country                                  
A Abkhazia                   289    GE-AB
Afghanistan                  412       AF
Albania                      276       AL
Algeria                      603       DZ

In [60]:
df4.loc['Algeria'], df4.iloc[1]  #index name or row

(Mobile country code                                           603
 ISO 3166                                                       DZ
 Mobile network codes      List of mobile network codes in Algeria
 National MNC authority                                        NaN
 Remarks                                                       NaN
 Name: Algeria, dtype: object,
 Mobile country code                                               412
 ISO 3166                                                           AF
 Mobile network codes      List of mobile network codes in Afghanistan
 National MNC authority                                            NaN
 Remarks                                                           NaN
 Name: Afghanistan, dtype: object)

In [67]:
df4.iloc[[0,6,7],[1,2,3]] #multiple rows and multiple column but multiple rows/column must be described as list

ISO 3166                      Mobile network codes  \
Country                                                                        
A Abkhazia                   GE-AB  List of mobile network codes in Abkhazia   
Angola                          AO    List of mobile network codes in Angola   
Anguilla (United Kingdom)       AI  List of mobile network codes in Anguilla   

                                         National MNC authority  
Country                                                          
A Abkhazia                                                  NaN  
Angola                                                      NaN  
Anguilla (United Kingdom)  Public Utilities Commission (PUC)[7]

In [70]:
df4.loc[['A Abkhazia','Algeria']] #multiple rows,index mentioned as list []

Mobile country code ISO 3166  \
Country                                    
A Abkhazia                  289    GE-AB   
Algeria                     603       DZ   

                                Mobile network codes National MNC authority  \
Country                                                                       
A Abkhazia  List of mobile network codes in Abkhazia                    NaN   
Algeria      List of mobile network codes in Algeria                    NaN   

                             Remarks  
Country                               
A Abkhazia  MCC is not listed by ITU  
Algeria                          NaN

In [88]:
df4.reset_index(inplace=True)  #reset index
# df4.set_index('Country',inplace=True)  #set index
df4

Country  level_0  index  \
0                                   A Abkhazia        0      0   
1                                  Afghanistan        1      1   
2                                      Albania        2      2   
3                                      Algeria        3      3   
4    American Samoa (United States of America)        4      4   
..                                         ...      ...    ...   
247                                    Vietnam      247    247   
248                        W Wallis and Futuna      248    248   
249                                    Y Yemen      249    249   
250                                   Z Zambia      250    250   
251                                   Zimbabwe      251    251   

     Mobile country code ISO 3166  \
0                    289    GE-AB   
1                    412       AF   
2                    276       AL   
3                    603       DZ   
4                    544       AS   
..                   ...      ...   
247                  452       VN   
248                  543       WF   
249                  421       YE   
250                  645       ZM   
251                  648       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 8 columns]

In [90]:
df4.drop('index',axis=1)   #drop index

0        0
1        1
2        2
3        3
4        4
      ... 
247    247
248    248
249    249
250    250
251    251
Name: index, Length: 252, dtype: int64