In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [3]:
df.to_csv('test.csv')

In [4]:
#accesing the elements
#1) .loc (row index)  2) .iloc (row and column index)
ds=df.loc['row1'] #data series
ds1=df.loc['row2']

#data frame contain more than one row and column
print(ds)
print(ds1)
print(type(ds))


col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int32
col1    4
col2    5
col3    6
col4    7
Name: row2, dtype: int32
<class 'pandas.core.series.Series'>


In [5]:
frame=df.iloc[:,:]  #same as numpy, #[row,column] [0:2,:] row: start from 0 and go before 2; : all columns
frame1=df.iloc[0:2,0:2]
frame2=df.iloc[0:2,0]
print(frame)
print(type(frame))  #type is data frame (multiple row and column)
print(frame1)
print(frame2)
print(type(frame2))  #data series as 1d array


      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19
<class 'pandas.core.frame.DataFrame'>
      col1  col2
row1     0     1
row2     4     5
row1    0
row2    4
Name: col1, dtype: int32
<class 'pandas.core.series.Series'>


In [6]:
df.iloc[:,1:]

col2  col3  col4
row1     1     2     3
row2     5     6     7
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [7]:
#convert the data frame into arrays
arr1=df.iloc[:,1:].values  #.values convert the data frame into array
print(arr1)
arr1.shape

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


(5, 3)

In [8]:
df.isnull().sum()  #check the null


col1    0
col2    0
col3    0
col4    0
dtype: int64

In [9]:
df['col1'].value_counts()  ## count the type of value in column 1, like 0 1time, 4 1 times

col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [10]:
#accesing the value by col name
print(df['col2'])

print(df[['col1','col2']])   #df['col1','col2']  will not work, need tobe mention as list

row1     1
row2     5
row3     9
row4    13
row5    17
Name: col2, dtype: int32
      col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17


In [11]:
df['col1'].unique()  #return unique value in col1


array([ 0,  4,  8, 12, 16])

In [12]:
df=pd.read_csv('mercedesbenz.csv')

In [13]:
df.head()   #top 5 rows

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [15]:
df.describe()  #it will describe only numeric fields

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [16]:
df['X0'].value_counts()  #count the value of categories iin column X0

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [17]:
df[df['y']>200]  #print the value where >100

ID       y X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
883  1770  265.32  y  r  ai  f  d  ag  l  t  ...     0     0     0     0   

     X379  X380  X382  X383  X384  X385  
883     0     0     0     0     0     0  

[1 rows x 378 columns]

In [4]:
from io import StringIO, BytesIO

In [19]:
data= ('col1,col2,col3\n''x,y,1\n''a,b,2\n''c,d,3')
type(data)  #str

str

In [20]:
StringIO

_io.StringIO

In [21]:
df1=pd.read_csv(StringIO(data)) #StringIO: Text I/O implementation using an in-memory buffer.
# read the data and store in a in-memory buffer and the read using read_csv
print(type(df1))  #data frame
print(df1)
print(type(df1['col3'][2]))


<class 'pandas.core.frame.DataFrame'>
  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3
<class 'numpy.int64'>


In [22]:
df2=pd.read_csv(StringIO(data),usecols=['col1','col3']) #use col1 nad 3 from the given csv
df2

col1  col3
0    x     1
1    a     2
2    c     3

In [23]:
df2.to_csv('Test1.csv') #create csv from the data frame

In [24]:
data1=('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,12\n')  #if () not given : unexpected indent error
data1

'a,b,c,d\n1,2,3,4\n5,6,7,8\n9,10,11,12\n'

In [25]:
df3=pd.read_csv(StringIO(data1), dtype=object)  #object mean string
df3

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [26]:
print(df3['a'][1])  ##string value
print(df3['a'])  #data type=object

5
0    1
1    5
2    9
Name: a, dtype: object


In [27]:
df4=pd.read_csv(StringIO(data1), dtype=float) #dtype= int, float
df4

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [28]:
#different column , different data type
df5=pd.read_csv(StringIO(data1),dtype={'a':int,'b':object,'c':float,'d':'Int64'})  #example: {'a': np.float64, 'b': np.int32, 'c': 'Int64'}
df5

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [29]:
print(type(df5['a'][0]))
print(df5.dtypes)  #check all the data types in columns

<class 'numpy.int32'>
a      int32
b     object
c    float64
d      Int64
dtype: object


In [30]:
data2=('index,a,b,c\n'
       '4,apple,bat,6\n'
       '5,orange,cow,8\n')
df6= pd.read_csv(StringIO(data2))
df6

index       a    b  c
0      4   apple  bat  6
1      5  orange  cow  8

In [31]:
#want to index column represt index of data frame; instead of 0,1

df=pd.read_csv(StringIO(data2),index_col=0)  #or index_col='index', by column name
df


a    b  c
index                
4       apple  bat  6
5      orange  cow  8

In [32]:
data3=('a,b,c\n'
       '4,apple,bat\n'
       '5,orange,cow\n')
df7= pd.read_csv(StringIO(data3),usecols=['b','c'])  #usecols=[1,2]
df7

b    c
0   apple  bat
1  orange  cow

In [33]:
data4='a,b\nhello, \\"Bob"\\, nice to \\see you|5,6'

df8=pd.read_csv(StringIO(data4),sep='|',escapechar='\\')  #escapechar will escape the char and will not consider
df8

a,b
hello, "Bob", nice to see you  5,6

In [34]:
import requests

In [35]:
# df9=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',sep='\t') #download the content and read on tab seperator
# df9

# headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
# s = requests.get('https://fineli.fi/fineli/en/elintarvikkeet/resultset.csv',headers=headers).content
# s


# Read Json to CSV

In [2]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
Data

'{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'

In [5]:
df1=pd.read_json(StringIO(Data)) #pd.read_json(Data); warning:Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
print(df1.head())

  employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...  


In [6]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None) #no header, tranfer the whole data into data frameb

In [7]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [8]:
df.to_csv('wine.csv')

In [9]:
df1.to_json() #default is index, thats why the json created with index-> column valu
#records' : list like [{column -> value}, ... , {column -> value}]
# - 'index' : dict like {index -> {column -> value}}

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [10]:
df1.to_json(orient='records') #now proper json created without indexing of data frame, only with values

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [ ]:
df.to_json(orient='records')  #df.to_json(orient='records')

# Reading HTML Content

In [27]:
import html5lib
# url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
url='https://en.wikipedia.org/wiki/Mobile_country_code'
dfh= pd.read_html(url,match='Mobile country code',header=0)
print(type(dfh))  #dfh is list of table present in that html page
df2=dfh[0]  #list to data frame, dfh[0] is the 1st table , i.e. data frame
print(type(df2))
print(df2)
df2.to_csv('html.csv',index=False) # Dont save the index (index=False)
# dfh.to_csv('html.csv')
# print(dfh[0])

<class 'list'>
<class 'pandas.core.frame.DataFrame'>
     Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe

In [29]:
df_excel=pd.read_excel('Excel_Sample.xlsx')  #sheet_name also can mentioned for specific sheet within excel

In [30]:
df_excel.head()

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

# Pickling
- 
All pandas objects are equipped with to_pickle methods which use Python’s cPickle module to save data structures to disk using the pickle format.

In [31]:
df_excel.to_pickle('df_excel') #create df_excel file

In [33]:
df=pd.read_pickle('df_excel') #read the saved pickle
df

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [34]:
df.head()

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15